"""Code generation for Bittensor miner boilerplate using Python 3.14 t-strings.

Python 3.14 t-strings (PEP 750) return a Template object instead of a str,
enabling safe, inspectable code generation where interpolations are explicit
and can be validated or transformed before emission.
"""

from __future__ import annotations

import textwrap
from pathlib import Path
from string.templatelib import Template

from torch2bt.models import ModelSignature, Optimization, PackageConfig, SubnetProtocol


def _render(template: Template) -> str:
    """Render a Python 3.14 t-string Template to a plain string.

    Unlike f-strings, t-strings do not auto-stringify; this renderer applies
    conversion flags (r, s, a) and format specs from each Interpolation explicitly.

    Args:
        template: The Template produced by a t"..." literal.

    Returns:
        The fully rendered string.
    """
    parts: list[str] = []
    for string, interp in zip(template.strings, (*template.interpolations, None), strict=False):
        parts.append(string)
        if interp is None:
            break
        value = interp.value
        if interp.conversion == "r":
            value = repr(value)
        elif interp.conversion == "s":
            value = str(value)
        elif interp.conversion == "a":
            value = ascii(value)
        fmt = interp.format_spec
        if isinstance(fmt, Template):
            fmt = _render(fmt)
        parts.append(format(value, fmt or ""))
    return "".join(parts)


def _indent(text: str, spaces: int) -> str:
    """Indent every non-empty line of text by the given number of spaces.

    Args:
        text: Multi-line string to indent.
        spaces: Number of leading spaces to add.

    Returns:
        The indented string.
    """
    return textwrap.indent(text, " " * spaces)


def generate_protocol(signature: ModelSignature, protocol: SubnetProtocol) -> str:  # noqa: ARG001
    """Generate protocol.py source for the target subnet.

    Args:
        signature: The inspected model I/O signature.
        protocol: The target subnet's protocol specification.

    Returns:
        Python source code string for protocol.py.
    """
    synapse_cls = protocol.synapse_class
    subnet_id = protocol.subnet_id
    subnet_name = protocol.name
    description = protocol.description

    all_fields = {**protocol.input_spec, **protocol.output_spec}
    field_lines = "\n    ".join(f"{name}: {typ} | None = None" for name, typ in all_fields.items())

    field_keys = list(all_fields)
    deserialize_items = ",\n            ".join(f'"{k}": self.{k}' for k in field_keys)
    deserialize_body = f"{{\n            {deserialize_items}\n        }}"

    return _render(t"""\
# Generated by torch2bt — do not edit manually.
# Target: SN{subnet_id} ({subnet_name})
from __future__ import annotations

import bittensor as bt


class {synapse_cls}(bt.Synapse):
    \"\"\"{description}\"\"\"

    {field_lines}

    def deserialize(self) -> dict:
        \"\"\"Deserialize synapse fields to a plain dict.\"\"\"
        return {deserialize_body}
""")


def generate_miner(
    signature: ModelSignature,
    protocol: SubnetProtocol,
    config: PackageConfig,
) -> str:
    """Generate miner.py that serves the model on a Bittensor Axon.

    Args:
        signature: The inspected model I/O signature.
        protocol: The target subnet's protocol specification.
        config: The package configuration.

    Returns:
        Python source code string for miner.py.
    """
    synapse_cls = protocol.synapse_class
    model_cls = signature.model_class_name
    model_mod = signature.model_module
    wallet = config.wallet_name
    subnet_id = protocol.subnet_id
    subnet_name = protocol.name
    precision_dtype = _optimization_dtype(config.optimization)

    input_fields = list(protocol.input_spec.keys())
    output_fields = list(protocol.output_spec.keys())

    extraction_lines = (
        "\n        ".join(f"# synapse.{f} — {protocol.input_spec[f]}" for f in input_fields)
        or "# no synapse input fields defined"
    )

    packing_lines = (
        "\n        ".join(
            f"# synapse.{f} = ...  — {protocol.output_spec[f]}" for f in output_fields
        )
        or "# no synapse output fields defined"
    )

    return _render(t"""\
# Generated by torch2bt — do not edit manually.
# Model: {model_cls} | Subnet: SN{subnet_id} ({subnet_name})
from __future__ import annotations

import logging
import time

import bittensor as bt
import torch

from {model_mod} import {model_cls}
from protocol import {synapse_cls}

logger = logging.getLogger(__name__)

WALLET_NAME = "{wallet}"
NETUID = {subnet_id}
PRECISION: torch.dtype = {precision_dtype}
SYNC_INTERVAL_SECS = 300
MIN_VALIDATOR_STAKE = 1_000.0


class Miner:
    \"\"\"Bittensor miner serving {model_cls} on SN{subnet_id} ({subnet_name}).\"\"\"

    def __init__(self) -> None:
        \"\"\"Initialize wallet, subtensor, axon, metagraph, and model.\"\"\"
        self.wallet = bt.wallet(name=WALLET_NAME)
        self.subtensor = bt.subtensor()
        self.metagraph = self.subtensor.metagraph(NETUID)
        self.axon = bt.axon(wallet=self.wallet)

        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        self.model = {model_cls}()
        self.model.eval()
        self._apply_precision()
        self.model.to(self.device)

        self.axon.attach(forward_fn=self.forward, blacklist_fn=self.blacklist)
        logger.info("Miner ready. wallet=%s netuid=%d device=%s precision=%s", WALLET_NAME, NETUID, self.device, PRECISION)

    def _apply_precision(self) -> None:
        \"\"\"Cast model weights to the configured precision.\"\"\"
        if PRECISION == torch.float16:
            self.model.half()
        elif PRECISION == torch.bfloat16:
            self.model.to(torch.bfloat16)

    def blacklist(self, synapse: {synapse_cls}) -> tuple[bool, str]:
        \"\"\"Reject requests from validators with insufficient stake.

        Args:
            synapse: The incoming synapse from a validator.

        Returns:
            A (reject, reason) tuple; reject=True drops the request.
        \"\"\"
        try:
            uid = self.metagraph.hotkeys.index(synapse.dendrite.hotkey)
        except ValueError:
            return True, "Hotkey not found in metagraph."
        stake = float(self.metagraph.S[uid])
        if stake < MIN_VALIDATOR_STAKE:
            return True, f"Insufficient stake: {{stake:.2f}} TAO < {{MIN_VALIDATOR_STAKE}} TAO"
        return False, ""

    async def forward(self, synapse: {synapse_cls}) -> {synapse_cls}:
        \"\"\"Handle an incoming synapse request and populate output fields.

        Args:
            synapse: The incoming synapse carrying input data from the validator.

        Returns:
            The synapse with output fields populated by the model.
        \"\"\"
        # --- Input extraction ---
        {extraction_lines}

        # --- Model inference ---
        try:
            with torch.inference_mode():
                pass  # Replace with: outputs = self.model(inputs)
        except RuntimeError:
            logger.exception("Model inference failed.")
            raise

        # --- Output packing ---
        {packing_lines}

        return synapse

    def run(self) -> None:
        \"\"\"Start the Axon and block until interrupted, syncing metagraph periodically.\"\"\"
        self.axon.start()
        self.subtensor.serve_axon(netuid=NETUID, axon=self.axon)
        logger.info("Axon live at %s", self.axon.external_ip)
        try:
            while True:
                time.sleep(SYNC_INTERVAL_SECS)
                self.metagraph.sync()
                logger.info("Metagraph synced. block=%d", self.metagraph.block.item())
        except KeyboardInterrupt:
            logger.info("Shutting down.")
        finally:
            self.axon.stop()


if __name__ == "__main__":
    import logging as _logging

    _logging.basicConfig(level=_logging.INFO, format="%(asctime)s %(levelname)s %(name)s: %(message)s")
    Miner().run()
""")


def generate_dockerfile(config: PackageConfig, protocol: SubnetProtocol) -> str:
    """Generate a Dockerfile for the containerised miner.

    Args:
        config: The package configuration.
        protocol: The target subnet's protocol specification.

    Returns:
        Dockerfile content as a string.
    """
    base_image = "pytorch/pytorch:2.5.0-cuda12.1-cudnn9-runtime"
    wallet = config.wallet_name
    subnet_id = protocol.subnet_id
    subnet_name = protocol.name

    return _render(t"""\
# Generated by torch2bt — Miner for SN{subnet_id} ({subnet_name})
FROM {base_image}

WORKDIR /app

RUN pip install --no-cache-dir uv

COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-dev

COPY miner.py protocol.py ./

ENV BT_WALLET_NAME={wallet}
ENV NETUID={subnet_id}
ENV PYTHONUNBUFFERED=1

EXPOSE 8091

ENTRYPOINT ["uv", "run", "python", "miner.py"]
""")


def generate_uv_project(protocol: SubnetProtocol, optimization: Optimization) -> str:
    """Generate a pyproject.toml for the miner's isolated uv environment.

    Args:
        protocol: The target subnet's protocol specification.
        optimization: The optimization strategy (may add extra deps like bitsandbytes).

    Returns:
        pyproject.toml content as a string.
    """
    subnet_id = protocol.subnet_id
    name = protocol.name
    extra_deps = (
        '    "bitsandbytes>=0.43",\n'
        if optimization in (Optimization.INT4, Optimization.INT8)
        else ""
    )

    return _render(t"""\
# Generated by torch2bt — Miner environment for SN{subnet_id} ({name})
[project]
name = "torch2bt-miner-sn{subnet_id}"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "torch>=2.5",
    "bittensor>=8.0",
{extra_deps}]

[tool.uv]
python-preference = "managed"
""")


def _optimization_dtype(opt: Optimization) -> str:
    """Return the torch.dtype attribute string for a given optimization level.

    Args:
        opt: The optimization strategy.

    Returns:
        A string like "torch.float32" for use in generated source code.
    """
    mapping: dict[Optimization, str] = {
        Optimization.FP32: "torch.float32",
        Optimization.FP16: "torch.float16",
        Optimization.BF16: "torch.bfloat16",
        Optimization.INT8: "torch.float16",
        Optimization.INT4: "torch.float16",
    }
    return mapping.get(opt, "torch.float32")


def write_package(
    output_dir: Path,
    protocol_src: str,
    miner_src: str,
    dockerfile_src: str,
    uv_project_src: str,
) -> dict[str, Path]:
    """Write all generated files to the output directory.

    Args:
        output_dir: Directory to write files into (created if absent).
        protocol_src: Content for protocol.py.
        miner_src: Content for miner.py.
        dockerfile_src: Content for Dockerfile.
        uv_project_src: Content for pyproject.toml.

    Returns:
        Mapping of role name to the written Path.
    """
    output_dir.mkdir(parents=True, exist_ok=True)

    files: dict[str, tuple[Path, str]] = {
        "protocol": (output_dir / "protocol.py", protocol_src),
        "miner": (output_dir / "miner.py", miner_src),
        "dockerfile": (output_dir / "Dockerfile", dockerfile_src),
        "uv_project": (output_dir / "pyproject.toml", uv_project_src),
    }

    paths: dict[str, Path] = {}
    for role, (path, content) in files.items():
        path.write_text(content, encoding="utf-8")
        paths[role] = path

    return paths
